### PR TITLE
Feat: custom type (closes #31)

### LINKED ISSUE #31: Option to manually type the prefix
We got prefixes like `fix` `feat` etc. But sometime you need to prefix your issue based on a ticket, e.g. `SGC-14`.  Maybe we can add the option, if there are no `types`, then we can type them in manually as input prompt.

### PR DESCRIPTION
**Pull request by JPeer264**
(ref: #31)

### CODE REVIEW

**Comment by yordis** [comment]
I would do `feat(TICKET-NUMBER) ...` instead of creating new types for this.

**Comment by JPeer264** [comment]
@yordis this is actually already implemented as `scope`

**Comment by JPeer264** [comment]
Actually what you suggested works too and is also imo much better to read. Unfortunately different companies have different rules - and e.g.: `PRE-21: this is a new commit` is one of them

**Comment by yordis** [comment]
@JPeer264 but then people can't assume the tags and other things from the type of the commit.

For the most part, that information is random metadata that you can't rely on.

This is why I think is better to put it as scope (since they kind of are)

**Comment by JPeer264** [comment]
I agree to 100% on this.

But still there are projects where this needs to be done (as some of the projects I am working on have this kinda rule). I guess I'll append your suggested method to the readme as well.

**Pull request merged**
