### PR TITLE
Feat: sgc --retry (closes #65)

### LINKED ISSUE #65: sgc retry
If a commit fails, e.g. because of commit hooks, then currently shows `Please resolve first and type 'git commit -m ...'`. `sgc retry` can automatically commit with the latest commit message. 

- save in a tempdir
- find it again with the hash of the project name

### PR DESCRIPTION
**Pull request by JPeer264**
@aichbauer any suggestions on how to test this?

### CODE REVIEW

**Comment by aichbauer** [comment]
Maybe you could make functions that read/writes the retry files and you call it in the `cli.js` so you have it separated from the cli input and then you could test if this function works properly?

Why are you rewriting some functions with `async/await` and others not?

**Comment by JPeer264** [comment]
@aichbauer tests added :+1:

**Comment by JPeer264** [comment]
I also did a little refactoring. Unfortunately it is in this PR, as it was too difficult to put it in another PR.

**Comment by aichbauer** [comment]
I will take a look into it as soon as possible.

**Pull request merged**
